let fruits = ['apple', 'banana', 'cherry'];
fruits.push('date'); 
console.log(fruits);
fruits.pop(); 
console.log(fruits);
fruits.unshift('avocado');
console.log(fruits);
fruits.shift(); 
console.log(fruits);
console.log(fruits.splice(1, 1)); 